### ISSUE TITLE
car_tuple的理解

### ISSUE THREAD

**Issue by GChasing** [hanruihua/RDA_planner#2]
请问代码中car_tuple中的G，h, wheelbase分别代表什么含义？

**Comment by hanruihua** [comment]
你好 

G和h的含义是基于 generalized inequality的概念，和机器人的形状相关，对于点x，如果 Gx<=h, 就代表x 是在机器人的内部。

wheelbase 是Ackermann车的 轴距，可以参考 https://en.wikipedia.org/wiki/Wheelbase
