### ISSUE TITLE
how to use polygon obstacles

### ISSUE THREAD

**Issue by Wangjiabao0** [hanruihua/RDA_planner#3]
The collision always happens when I set the obstacles as polygon (square). Do I need to change some parameters?
![1](https://github.com/hanruihua/RDA_planner/assets/153971970/6d62f97c-c850-43a3-a775-bfa78f90cd30)

**Comment by hanruihua** [comment]
Hi, thank you for your interest in my work.

I believe the likely reason is the order of the vertices set in the yaml file. They should be in counterclockwise order.  You can verify the order.

**Comment by Wangjiabao0** [comment]
> Hi, thank you for your interest in my work.
> 
> I believe the likely reason is the order of the vertices set in the yaml file. They should be in counterclockwise order. You can verify the order.

The problem was properly solved, by setting vertices as ccw order. Thanks !!
