### ISSUE TITLE
为什么LamMuZ_cost_cons函数中计算cost时indep_Im_lamMuZ前加cp.neg

### ISSUE THREAD

**Issue by renjieDLUT** [hanruihua/RDA_planner#4]
![image](https://github.com/hanruihua/RDA_planner/assets/41196373/d115c8f1-9fe0-4e7a-9aca-a7906070b565)

在代码实现时,为什么加上了 cp.neg?

**Comment by hanruihua** [comment]
详情已回邮件

cp.neg 是为减少迭代次数的工程化改进
论文公式版本见分支 dev_acce: https://github.com/hanruihua/RDA_planner/tree/dev_acce
