### ISSUE TITLE
Lidar_nav仿真不能完整跟踪路径

### ISSUE THREAD

**Issue by Wangjiabao0** [hanruihua/RDA_planner#5]
![image](https://github.com/user-attachments/assets/661a93a8-2d62-4cf8-af21-bf45f998b026)
您好，我在运行lidar_path_track.py文件时仅保留一个障碍物。通过该障碍物后（后续路径不存在障碍物），自车直接停在图示位置直至仿真迭代(i=500)结束。

**Comment by hanruihua** [comment]
你好   

这个大概率是某些变量值没有清零的原因引起的，刚修复了这个bug，可以更新到最新的版本再尝试运行。

Translation:

Hi,

This probelm may be caused by the  Non-zero values in some cvxpy parameters. I have fixed this bug, you can update the newest version of the code to run your example again.
