### ISSUE TITLE
Issue when splitting reference path by gear

### ISSUE THREAD

**Issue by Matrix97l** [hanruihua/RDA_planner#6]
https://github.com/hanruihua/RDA-planner/blob/05aa21610a78f3075f63870fbc5fc73457a246cf/RDA_planner/mpc.py#L249

I think this line should be changed as shown below.

```python
curve_list.append(ref_path[start_index:])
```

When the input ref_path has the same gear value at every step, using "end_index:" would make the output path only contain ref_path[end_index]. This change would not cause issues in other scenarios, as "start_index = end_index" is stated in line 246.

**Comment by hanruihua** [comment]
Thank you for pointing out this issue.

I have updated the function as follows to resolve it:

![code](https://github.com/user-attachments/assets/9b8e8a86-5dc7-4507-ba17-452bb5b15cfc)

**Comment by Matrix97l** [comment]
Thanks!
